name: Make dist package on new tag

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2

      - name: Install packages requries for building
        run: sudo apt install -y autotools-dev autoconf gettext build-essential

      - name: Bootstrap
        run: ./bootstrap
        
      - name: Configure
        run: ./configure

      - name: Make dist
        run: make dist

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            boot-server-*.tar.gz
