name: Make dist package on new tag

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages requries for building
        run: DEBIAN_FRONTEND=noninteractive apt install -y autotools-dev autoconf gettext build-essential

      - name: Bootstrap
        run: ./bootstrap

      - name: Make dist
        run: make dist

      - name: Upload artefact
      - uses: actions/upload-artifact@v3
        with:
          name: dist-packages
          path: boot-server-*.tar.gz
